apiVersion: apps/v1
kind: Deployment
metadata:
  name: backened-deployment
  labels:
    app: backened-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backened-deployment
  template:
    metadata:
      labels:
        app: backened-deployment
    spec:
      containers:
      - name: backened-deployment
        image: gcr.io/devops-project-368608/development/be-my@sha256:4214abe58ca1d1485f06b4b7a6e6bb5053d4fc13f08c159fb7c5ba598e7a9cbf
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: backened-service
  namespace: default
spec:
  ports:
  - nodePort: 30028
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: backened-deployment
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backened-ingress
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: "myapps.sathya.shop"
    http: 
      paths: 
      - path: /books
        pathType: Prefix
        backend:
          service: 
            name: backened-service
            port:
              number: 3001